-- Antidep — lokal seed
--
-- Kjøres bare av lokal `supabase db reset`. Filen er reservert for rent lokale
-- demodata og skal aldri brukes til å gjeninnføre klinisk prototypeinnhold.
--
-- Kontrollert katalog/vokabular som selve skjemaet trenger, ligger i de
-- versjonerte migrasjonene. Aktive evidensfunn, synteser, vurderinger eller
-- publiseringskandidater skal ikke seedes her.
--
-- Filen er foreløpig tom med vilje. Se docs/EVIDENCE_PIPELINE.md og
-- supabase/README.md for gjeldende arkitektur og lokal testflyt.
